### ISSUE TITLE
Some related data

### ISSUE THREAD

**Issue by amitness** [okfnepal/localboundaries#1]
Not exactly geojson, but might be useful for mapping names: [federal-nepal](https://github.com/amitness/federal-nepal)

**Comment by kshitizkhanal7** [comment]
https://www.npmjs.com/package/new-nepal-topojson
related topojson here

**Comment by nikeshbalami** [comment]
Thank You @amitness and @kshitizkhanal7 dai for the references, we are targeting tonight or tomorrow morning for the launch, Looking forward to your active participation in this repo.

**Comment by nikeshbalami** [comment]
Hello, We are going public for feedback from today, although there is some work left. Drop your feedback if you have any: https://okfnepal.github.io/localboundaries/
