### ISSUE TITLE
Total number of Page Visit and Downloads

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/localboundaries#2]
I would be awesome if we can add the Page Visit and Downloads counts. This can help us to track how many people had played or used the data. Later we can show the government how useful it would be to open up boundaries data.

**Comment by amitness** [comment]
Anyone taking up the issue, see this: [Google Short URL API](https://developers.google.com/url-shortener/v1/getting_started#url_analytics)

**Comment by nikeshbalami** [comment]
Currently, I am looking for someone who can work on this @amitness. We have used the Shorten URL to count downloads but what I really want is to show that downloads count at home page so that others too can know how many had downloaded it. @sagargg have you looked at this previously, that looks easy :)
